name: Node CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
  TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  NEXT_PUBLIC_TINA_BRANCH: ${{ github.head_ref }}
  NODE_OPTIONS: '--max_old_space_size=4096'
  TINA_SEARCH_TOKEN: ${{ secrets.TINA_SEARCH_TOKEN }}
  UNOPTIMIZED_IMAGES: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm i
      - name: pnpm build
        run: pnpm build
      - name: pnpm lint
        run: pnpm lint
      - name: pnpm test
        run: pnpm test
        env:
          CI: true
      - name: pnpm export
        run: |
          pnpm export
        env:
          CI: true
      - name: ðŸ“‰ Check HTML
        uses: anishathalye/proof-html@v1.4.0
        with:
          directory: './out'
          enforce_https: false
          check_img_http: false
          check_external_hash: false
          empty_alt_ignore: true
          url_ignore_re: '/.+\/(blog|404)\/.+/'
