name: TEST2

on:
  repository_dispatch:
    types: [vercel-deployment]  
  workflow_dispatch:            
  deployment_status:
    types: [success]            

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print full event payload
        run: |
          echo "GitHub event name: ${{ github.event_name }}"
          echo "------ FULL PAYLOAD ------"
          echo '${{ toJson(github.event) }}'
