name: TEST - Dump Vercel Event

on:
  repository_dispatch:
  deployment_status:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print full event payload
        run: |
          echo "GitHub event name: ${{ github.event_name }}"
          echo "------ FULL PAYLOAD ------"
          echo '${{ toJson(github.event) }}'
